---
- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
  - brew

- name: Homebrew Tap
  command: brew tap {{ item }}
  loop: '{{ homebrew_taps }}'
  tags:
  - brew

- name: Install homebrew packages
  ignore_errors: true
  community.general.homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask packages
  command: brew install --cask {{ item }}
  ignore_errors: true
  loop: '{{ homebrew_cask_packages }}'
  tags:
  - brew

- name: Homebrew cleanup
  command: brew cleanup
...