---
- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
  - brew

- name: Install homebrew packages
  community.general.homebrew:
    name: '{{ item }}'
    state: latest
  loop: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask packages
  command: brew install --cask {{ item }}
  ignore_errors: yes
  loop: '{{ homebrew_cask_packages }}'
  tags:
  - brew

- name: Tap Homebrew fonts cask
  command: brew tap homebrew/cask-fonts

- name: Install Nerd Font
  command: brew install --cask font-fira-code-nerd-font

- name: Homebrew cleanup
  command: brew cleanup
...